version: '3'
services:
  pdf-document-layout-analysis-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVICE_URL=http://host.docker.internal:3000
    runtime: nvidia