services:
  pdf-document-layout-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--chdir", "./src", "app:app", "--bind", "0.0.0.0:5060", "--timeout", "10000"]
    init: true
    restart: unless-stopped
    ports:
      - "5060:5060"
    env_file:
      - .env
    environment:
      - SERVICE_URL=http://host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"