apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrq
  namespace: chunkmydocs
  labels:
    app.kubernetes.io/name: rrq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rrq
  template:
    metadata:
      namespace: chunkmydocs
      labels:
        app.kubernetes.io/name: rrq
    spec:
      containers:
      - name: rrq
        image: luminainc/rrq:fa7b3f7
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: rrq-secrets
        ports:
        - containerPort: 8000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
---   
apiVersion: v1
kind: Service
metadata:
  name: rrq-service
  namespace: chunkmydocs
  labels:
    app.kubernetes.io/name: rrq
spec:
  selector:
    app.kubernetes.io/name: rrq
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
