[project]
name = "task"
version = "0.1.0"
description = "Run tasks on documents on either cpu or gpu"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bentoml>=1.3.5",
    "opencv-python>=4.10.0.84",
    "paddleocr>=2.8.1",
    "pydantic>=2.9.1",
    "requests>=2.32.3",
    "torch>=2.4.1",
    "transformers>=4.44.2",
]


