[project]
name = "task"
version = "0.1.0"
description = "Run tasks on documents on either cpu or gpu"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "bentoml>=1.3.5",
    "more-itertools>=10.5.0",
    "opencv-python>=4.10.0.84",
    "openpyxl>=3.1.5",
    "paddleocr>=2.8.1",
    "pydantic>=2.9.1",
    "rapid-latex-ocr>=0.0.8",
    "requests>=2.32.3",
    "torch>=2.4.1",
    "transformers>=4.44.2",
]


