apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-processor
  namespace: task-processor
  labels:
    app.kubernetes.io/name: task-processor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: task-processor
  template:
    metadata:
      namespace: task-processor
      labels:
        app.kubernetes.io/name: task-processor
    spec:
      containers:
      - name: task-processor
        image: luminainc/task-processor:961e6c6
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
